version: "3"
services:
  empl-app:
    image: xfneo/employees-management-ws:latest
    container_name: empl_app
    environment:
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_HOST: empl-db
      DB_PORT: 5432
      DEPARTMENTS_SERVICE_URL: http://dept-app:8080
    ports:
      - 8080:8080
    links:
      - empl-db
    restart: always
  empl-db:
    image: postgres:11-alpine
    container_name: empl_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: employees_service
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ~/pg_data_empl:/var/lib/postgresql/data/pgdata
    restart: always
  dept-app:
    image: xfneo/departments-management-ws:latest
    container_name: dept_app
    environment:
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_HOST: dept-db
      DB_PORT: 5432
      EMPLOYEES_SERVICE_URL: http://empl-app:8080
    ports:
      - 8081:8080
    links:
      - dept-db
    restart: always
  dept-db:
    image: postgres:11-alpine
    container_name: dept_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: departments_service
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ~/pg_data_dept:/var/lib/postgresql/data/pgdata
    restart: always
